package main.java.it.unibo.bioassault.model.stats;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import it.unibo.bioassault.model.viruses.Virus;

/**
 * Tracks, measures, and encapsulates all player performance metrics throughout a single gameplay session.
 * Provides APIs to increment real-time stats (kills, damage, resources collected) and contains the 
 * game design algorithms to compute final high scores and end-of-run summaries.
 */

public class RunStats{
    private static final float SECOND_TO_MINUTES = 60;    
    private static final long KILLS_MULTIPLIER = 10L;
    private static final float DAMAGE_MULTIPLIER = 0.5f;
    private static final int SURVIVING_BONUS = 2;
    private static final long LEVEL_BONUS = 500L;
    private static final long MAX_SPEED_BONUS = 10_000L;
    private static final long BONUS_REDUCER = 10L;
    private final long startTimeMs = System.currentTimeMillis();
    private long endTimeMs = 0;

    private int kills = 0;
    private int eliteKills = 0;
    private int bossKills = 0;
    private long totalXp      = 0;
    private int goldCollected= 0;
    private float damageDealt  = 0;
    private float damageTaken  = 0;
    private int healUsed    = 0;
    private boolean survived     = false;

    private final Map<String, Integer> killsByType = new HashMap<>();

    
    
    /**
     * Records an individual enemy kill, classifying it by identity group and difficulty rank.
     * * @param enemyType The string identifier representing the species or type of enemy killed.
     * @param elite     True if the killed target was classified as an elite variant.
     * @param boss      True if the killed target was classified as a boss entity.
     */
    public void recordKill (final boolean elite, final boolean boss) {
        kills++;
        killsByType.merge(enemyType, 1, Integer::sum);
        
        if(elite) {
            eliteKills++;
        }

        if(boss) {
            bossKills++;
        }
    }

    /**
     * Accumulates experience points acquired during the session.
     * * @param amount The quantity of experience points to add.
     */
    public void addXP(double amount) {
        totalXp += (long) amount;
    }

    /**
     * Increments the total amount of currency collected during the run.
     * * @param amount The numeric amount of gold found.
     */
    public void addGold(int amount) {
        goldCollected += amount;
    }

    /**
     * Records offensive output generated by the player.
     * * @param dmg Total raw or computed damage dealt to opposing units.
     */
    public void addDamageDealt(float dmg) {
        damageDealt += dmg;
    }

    /**
     * Records defensive damage sustained by the player.
     * * @param dmg Total incoming damage received from enemy impacts.
     */
    public void addDamageTaken(float dmg) {
        damageTaken += dmg;
    }

    /**
     * Increments the historical total counter tracking healing items or triggers consumed.
     */
    public void recodHeal() {
        healUsed++;
    }

    /**
     * Explicitly halts session measurements, anchoring the timestamp for calculations.
     * * @param survived True if the run concluded with a win state; false if premature casualty.
     */
    public void endRun(boolean survived) {
      this.survived = survived;
      this.endTimeMs = System.currentTimeMillis();  
    }

    /**
     * Calculates the exact elapsed duration the player survived or played during this specific run.
     * * @return A {@link Duration} instance mapping total elapsed survival time.
     */
    public Duration getSurvivalTime() {
        long end = endTimeMs > 0 ? endTimeMs : System.currentTimeMillis();
        return Duration.ofMillis(end- startTimeMs);
    }

    /**
     * Determines pacing efficiency by computing total kills scaled per minute.
     * * @return Float average of kills completed per individual minute.
     */
    public float getKillsPerMinute(){
        double  minutes = getSurvivalTime().toSeconds() / SECOND_TO_MINUTES;
         return minutes > 0 ? kills / (float) minutes : 0;
    }

    /**
     * Implements core balancing algorithms to compute the player's definitive final score.
     * Combines kills, experience, and damage, processing situational scaling bonuses.
     * * @param level The terminal player level achieved by session end.
     * @return Total structured score ranking numeric.
     */
    public long computeFinalScore(int level){
        long baseScore = (long)(kills * KILLS_MULTIPLIER + totalXp + damageDealt * DAMAGE_MULTIPLIER);

        if(survived) {
            baseScore *= SURVIVING_BONUS;
        }

        baseScore += level * LEVEL_BONUS;

        long seconds = getSurvivalTime().toSeconds();
        if(seconds > 0) {
            baseScore += Math.max(0, MAX_SPEED_BONUS - seconds * BONUS_REDUCER);
        }

        return baseScore;
    }

        public String toSummaryString(int level, List<Upgrade> upgrades) {
        Duration time = getSurvivalTime();
        long finalScore = computeFinalScore(level);

        StringBuilder sb = new StringBuilder();
        sb.append("╔══════════════════════════════════════════╗\n");
        sb.append(survived
            ? "║          ✨  VITTORIA!  ✨                ║\n"
            : "║          💀  GAME OVER  💀                ║\n");
        sb.append("╠══════════════════════════════════════════╣\n");
        sb.append(String.format("║  Livello raggiunto : %-22d║\n", level));
        sb.append(String.format("║  Tempo sopravvisuto: %02d:%02d              ║\n",
            time.toMinutes(), time.toSecondsPart()));
        sb.append("╠══════════════════════════════════════════╣\n");
        sb.append(String.format("║  Nemici eliminati  : %-22d║\n", kills));
        sb.append(String.format("║    di cui élite    : %-22d║\n", eliteKills));
        sb.append(String.format("║    di cui boss     : %-22d║\n", bossKills));
        sb.append(String.format("║  Kill/minuto       : %-22.1f║\n", getKillsPerMinute()));
        sb.append("╠══════════════════════════════════════════╣\n");
        sb.append(String.format("║  XP totale         : %-22d║\n", totalXp));
        sb.append(String.format("║  Oro raccolto      : %-22d║\n", goldCollected));
        sb.append(String.format("║  Danno inflitto    : %-22.0f║\n", damageDealt));
        sb.append(String.format("║  Danno subito      : %-22.0f║\n", damageTaken));
        sb.append("╠══════════════════════════════════════════╣\n");
        sb.append("║  Upgrade scelti:                         ║\n");
        upgrades.forEach(u -> sb.append(String.format("║    • %-38s║\n", u.getName())));
        sb.append("╠══════════════════════════════════════════╣\n");
        sb.append(String.format("║  ★  PUNTEGGIO FINALE: %-21d║\n", finalScore));
        sb.append("╚══════════════════════════════════════════╝\n");
        return sb.toString();
    }
}